### ISSUE TITLE
[Other] About attendance of "Practice Session 6 Q3 Hint" Lecture video

### ISSUE THREAD

**Issue by LilactheGreat** [goldshakil/ElectricalProgrammingCourse2020#193]
Hello, professor.

I found out that i missed the Lecture "Practice Session 6 Q3 Hint" in week 9.
I did practice session homework with help from "Practice Session 6" guide lecture and uploaded it on icampus. At that time, there was no "Practice Session 6 Q3 Hint" lecture. But i am pretty sure it was uploaded after tuesday.

As a result, i am marked as not attedent in this lecture video.

I know that it's my fault for not checking the newly uploaded lecture.

However, i feel somehow sad that i will get a minus point from this.
So, what i want to ask is as i did not watch this lecture in a fixed period, am i really getting minus point? or it will be okay because it is an hint lecture.

Thank you in advance.

**Comment by goldshakil** [comment]
I will extend the deadline to watch it but only this time.
please check the video before the end of the week every time as I will not extend the deadline next time.

**Comment by LilactheGreat** [comment]
Thank you, professor.
I will keep it in mind not to miss lectures.
