### ISSUE TITLE
[Others] about my score assigned to assignment1 & late submission

### ISSUE THREAD

**Issue by Kwon2s0081** [goldshakil/ElectricalProgrammingCourse2020#47]
I just confirmed that my assignment 1 has a score of zero, and I'm leaving a comment to ask if I can correct the task if it's because of the contents. Assignment2 was not submitted by the 29th due to a mistake, but I'd like to ask if the late submission project has any impact. There was a mistake on the date of the assignment, and I think there was a mistake because it was so new and awkward about the situation I'm going through. I will never let this happen again, and I'm sorry and ashamed that I'm the only one who seems to be doing this and causing this problem. Thank you for reviewing it.

**Comment by goldshakil** [comment]
can you send me a personal msg in Icampus? 
I will follow up with your situation. You don't have to worry

**Comment by Kwon2s0081** [comment]
Alas, I was mistaken about getting zero. By the way, are the assignments that I couldn't submit in the deadline just zero points?
